/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andre' at '04/02/16 15:36' with Gradle 2.9
 *
 * @author andre, @date 04/02/16 15:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
